### PR TITLE
Add support for stable doc URLs

### LINKED ISSUE #341: Ensure documentation pages have stable URLs
The recent changes I made changed some URLs. This is not a good idea (see: “[Cool URIs don't change](https://www.w3.org/Provider/Style/URI.html)”).

On the other hand, embracing Doxygen features is probably a good idea for better documentation with cross references, etc.

On solution I see is to add redirections: see e.g. [this example](https://stackoverflow.com/a/51175138).

### PR DESCRIPTION
**Pull request by wismill**
Doc URLs may change with time because they depend on Doxygen machinery. This is unfortunate because it is good practice to keep valid URLs (see: https://www.w3.org/Provider/Style/URI.html).

This commit adds a registry of URLs that has three functions:
- Check no previous URL is invalid.
- Add aliases for moved pages.
- Generate redirection pages for aliases.

Fixes #341

### CODE REVIEW

**Review by bluetech — APPROVED** [review]
Looks great to me, thanks!

**Comment by bluetech** [comment]
@wismill can you shoot me an email (my address should be visible in https://github.com/bluetech or in git logs) - I'd like to invite to you to be a member of @xkbcommon/maintainers so you can merge this yourself :)

**Comment by wismill** [comment]
@bluetech thank you for the invitation, I sent you an email. Please check your spam, as my domain wismill.eu is not always treated gently by servers 😒

**Comment by wismill** [comment]
The CI correctly caught the missing doc pages that I intentionally left unfixed. Now let’s check if it works with the updated registry.

**Pull request merged**
