### PR TITLE
Keysyms update

### LINKED ISSUE #358: Update keysyms
There have been multiple updates in [xorgproto](https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/commits/master/include/X11/keysymdef.h), not yet reflected in in xkbcommon.

Let’s do this when all other PR planned for [1.6.0](https://github.com/xkbcommon/libxkbcommon/milestone/1) are merged, to avoid possible conflicts.

### PR DESCRIPTION
**Pull request by wismill**
Fixes #358

*NOTE:* wait for the following MR in `xorgproto` to be merged:

- [ ] [Normalize keysyms header files](https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/merge_requests/80)
- [ ] [Update XF86Keysyms.h](https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/merge_requests/82)

Then the commit message should be updated with the correct `xorgproto` commit ref.

### CODE REVIEW

**Comment by wismill** [comment]
The test `x11comp` is failing because we need `xkbcomp` compiled with `x11proto-dev` 2023.2, but none of the Ubuntu release has this recent version. The test passes on my computer (openSUSE Tumbleweed).

**Comment by wismill** [comment]
`x11comp` test fixed with an ugly hack.

**Review by bluetech — APPROVED** [review]
LGTM, feel free to merge once xorgproto is ready

**Comment by wismill** [comment]
Rebased, updated with latest xorgproto, reworked commits. Will merge when CI is successful.

**Pull request merged**
