### PR TITLE
Prevent recursive includes of keymap components

### PR DESCRIPTION
**Pull request by wismill**
Prevent recursive includes of keymap components:

- Add file name property to `XkbFile`. This allow better identification of the file being processed.
- Add check for recursive includes of keycodes, key types, compat and symbols keymap components.
- Add tests for recursive includes.

I would like to get the design right wrt further work on #390.

### CODE REVIEW

**Comment by wismill** [comment]
There seems to be memory leaks in _key types_ code that make the test suite failed when runing with valgrind.

**Comment by wismill** [comment]
Fixed memory leak. I found some other leaks and grouped them in #391.

This PR will need to be rebase once #391 is merged.

**Comment by bluetech** [comment]
A simpler and arguably more robust method for detecting include loops is to have an include depth limit. Have you considered it?

**Comment by wismill** [comment]
@bluetech I did, but then I thought it would be cleaner to do an exact check that:
- avoids cycling completely: check occurs _before_ loading the recursive file.
- provides useful log message.

I guess this issue is unlikely enough that we could just do as you propose. I have no idea what is the depth threshold in `xkeyboard-config`. I guess __15__ is a reasonable threshold, with plenty of margin for keymaps in the wild.

**Comment by wismill** [comment]
Created an alternative design in #392.

**Pull request closed without merging**
